name: Build and Release Maven Project

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get previous tag
        id: get_previous_tag
        run: |
          git fetch --tags
          echo "prev_tag=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))" >> $GITHUB_ENV
        shell: bash

      - name: Generate commits list from previous tag
        id: generate_commits
        run: |
          echo "Automated build including those changes:" > release_body.txt
          git log ${prev_tag}...HEAD --oneline --pretty=format:"- %s" >> release_body.txt

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven (jlink)
        run: mvn clean javafx:jlink

      - name: Prepare Package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path target/TicTacToeFX -DestinationPath TicTacToeFX-Windows.zip

      - name: Prepare Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czvf TicTacToeFX-Linux.tar.gz -C target TicTacToeFX

      - name: Prepare Package (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          tar -czvf TicTacToeFX-Mac.tar.gz -C target TicTacToeFX

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TicTacToeFX-Windows.zip
            TicTacToeFX-Linux.tar.gz
            TicTacToeFX-Mac.tar.gz
          body_path: ./release_body.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
